main: main.dagrouphardcore.GroupHardcore
name: DaGroupHardcore
version: 1.2
author: lejara
description: Hardcore minecraft using a pool of lives
commands:
  setlives:
    description: Set the number of lives
    usage: /setlives [numOfLives]
    permission: dagrouphardcore.mycommand
    permission-message: You don't have the DaGroupHardcore.setlives permission.
  setdays:
    description: Set the number of days
    usage: /setdays [numOfdays]
    permission: dagrouphardcore.mycommand
    permission-message: You don't have the DaGroupHardcore.setlives permission.  
  reset:
    description: Resets the current number of lives
    usage: /resetlives
    permission: dagrouphardcore.mycommand
    permission-message: You don't have the DaGroupHardcore.setlives permission
  setworldend:
    description: Sets the world end event to happend when you fail the hardcore
    usage: /setworldend {[0] | [1]]}
    permission: dagrouphardcore.mycommand
    permission-message: You don't have the DaGroupHardcore.setlives permission
  resetplayerspawn:
    description: resets all online players spawn point to the world spawn point
    usage: /resetplayerspawn
    permission: dagrouphardcore.mycommand
    permission-message: You don't have the DaGroupHardcore.setlives permission     