main: main.lagrouphardcore.GroupHardcore
name: LaGroupHardcore
version: 1.0
author: lejara
description: Hardcore minecraft using a pool of lives
commands:
  setlives:
    description: Set and Resets the number of lives
    usage: /setlives [numOfLives]
    permission: lagrouphardcore.mycommand
    permission-message: You don't have the LaGroupHardcore.setlives permission.
  resetlives:
    description: Resets the current number of lives
    usage: /resetlives
    permission: lagrouphardcore.mycommand
    permission-message: You don't have the LaGroupHardcore.setlives permission
  setworldend:
    description: Sets the world end event to happend after you have failed the hardcore world
    usage: /setworldend {[0] | [1]]}
    permission: lagrouphardcore.mycommand
    permission-message: You don't have the LaGroupHardcore.setlives permission
  resetplayerspawn:
    description: resets all online players spawn point
    usage: /resetplayerspawn
    permission: lagrouphardcore.mycommand
    permission-message: You don't have the LaGroupHardcore.setlives permission     